### ISSUE TITLE
running docker-compose

### ISSUE THREAD

**Issue by drondeseries** [TheImaginear/dynamixX#6]
>  services:
  dynamiX:
    image: clharrel/dynamix:latest
    container_name: dynamiX
    user: 1000:1000
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
    ports:
      - 8090:80
    volumes:
      - /home/mediaserver/docker/data/dynamiX/config.json:/app/config.json
      - /home/mediaserver/docker/data/dynamiX/dynamiXHeadless.py:/app/dynamiXHeadless.py
      - /home/mediaserver/docker/data/dynamiX/:/app
    restart: unless-stopped 

    Error: 

    python: can't open file '/app/dynamiXHeadless.py': [Errno 2] No such file or directory 
    
    fix and running.

**Comment by character-not-found** [comment]
Hey @drondeseries ,

I was going around with a lot of trouble to get this working with Docker Compose (mostly because the script runs in a loop with the default config file and it is hard to interrupt it to get into the console to debug). Essentially, what I did to get it working was to mount only the base volume. Make sure that the dynamiXHeadless.py file in your mediaserver path is the one that is pulled from the image, and not just a rename of the dynamiX.py file included in the Windows version. 

Here is my compose if that helps:

> 
```
  dynamix:
    image: clharrel/dynamix:latest
    container_name: dynamix
    restart: unless-stopped
    volumes:
      - '${FOLDER_FOR_DATA:?err}/dynamix:/app'
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
    networks:
      - ${MEDIANETWORK:?err}

```

Inside of my "dynamix" local folder I had:
- config.json (adapted to my needs)
- dynamiXHeadless.py (again, the code inside of the docker pull, I can send you the code if you need it)
- requirements.txt (from the pull)
- user_exemptions.json

If it helps, and it certainly did it help me, I ran the Windows version first to build the .json files first and then moved them to the right place.

Hope this helps.
